from .workouts import workout_list
from .workouts_details import workout_details
from .workout_exercises import workout_exercises
from .sign_up import sign_up
from .profile import profile_view
from .change_profile import change_profile
from .user_posts import user_posts
from .new_post import create_post
from .new_comment import create_comment
from .following_search import following_search
from .follows_list import my_follows
from .follow_user import follow_view, unfollow_view
from .add_progress import add_progress
from .progress_list import progress_list
from .followings_posts import followings_posts
from .reaction_post import reaction_post
from .payment import payment_view
from .payment_sucessfull import payment_successful_view
from .contact import contact_form
from .calories import calories_intake
from .admin_views.goals import goal_list
from .admin_views.disabilities import disability_list
from .admin_views.exercises import exercise_list
from .admin_views.workouts import workoutadmin_list
from .admin_views.workouts import workoutplan_list
from .settings import settings